from __future__ import annotations

import json
import platform
import subprocess
import time
from dataclasses import dataclass
from pathlib import Path

import pathspec

MAX_INDEXED_PATHS = 750
DENY_PATTERNS = [
    "**/.env",
    "**/.env.*",
    "**/secrets.json",
    "**/.ssh/**",
    "**/.git/**",
    "**/.codegraph/**",
    "**/node_modules/**",
    "**/.venv/**",
    "**/__pycache__/**",
    "**/content-agents/sessions/**",
]


@dataclass(frozen=True)
class WorkspaceMap:
    root: Path
    file_count: int
    truncated: bool
    languages: tuple[str, ...]
    package_managers: tuple[str, ...]
    important_paths: tuple[str, ...]
    entrypoints: tuple[str, ...]
    docs: tuple[str, ...]
    tests: tuple[str, ...]
    commands: tuple[str, ...]
    git_branch: str | None
    git_dirty: bool | None

    def render(self) -> str:
        lines = [
            "# Workspace map",
            "",
            (
                "Navigation aid generated by the kernel. It is not proof that files "
                "were read; inspect targeted source before editing or making claims."
            ),
            f"- Root: `{self.root}`",
            f"- OS: {platform.system().lower()}",
            f"- Files indexed: {self.file_count}{' (bounded)' if self.truncated else ''}",
            f"- Languages: {', '.join(self.languages) or 'none detected'}",
            f"- Package managers: {', '.join(self.package_managers) or 'none detected'}",
            (
                f"- Git: {self.git_branch or 'not a repository'}, "
                f"{'dirty' if self.git_dirty else 'clean'}"
                if self.git_dirty is not None else "- Git: unavailable"
            ),
        ]
        for title, values in (
            ("Important paths", self.important_paths),
            ("Entrypoints", self.entrypoints),
            ("Docs", self.docs),
            ("Tests", self.tests),
            ("Commands", self.commands),
        ):
            lines.extend(["", f"## {title}"])
            lines.extend(f"- `{value}`" for value in values[:20])
            if not values:
                lines.append("- none detected")
        return "\n".join(lines)


class WorkspaceMapService:
    """Build and briefly cache a bounded, secret-safe project navigation map."""

    def __init__(self, ttl_seconds: float = 20) -> None:
        self.ttl_seconds = ttl_seconds
        self._cache: dict[Path, tuple[float, WorkspaceMap]] = {}

    def build(self, root: Path) -> WorkspaceMap:
        resolved = root.resolve()
        cached = self._cache.get(resolved)
        if cached and time.monotonic() - cached[0] < self.ttl_seconds:
            return cached[1]
        patterns = list(DENY_PATTERNS)
        gitignore = resolved / ".gitignore"
        if gitignore.is_file():
            patterns.extend(
                gitignore.read_text(encoding="utf-8", errors="replace").splitlines()
            )
        spec = pathspec.GitIgnoreSpec.from_lines(patterns)
        files: list[Path] = []
        truncated = False
        for path in sorted(resolved.rglob("*")):
            if len(files) >= MAX_INDEXED_PATHS:
                truncated = True
                break
            if not path.is_file():
                continue
            relative = path.relative_to(resolved).as_posix()
            if spec.match_file(relative):
                continue
            files.append(path)
        relative_files = [path.relative_to(resolved).as_posix() for path in files]
        suffixes = {path.suffix.lower() for path in files}
        languages = []
        for name, extensions in (
            ("python", {".py"}),
            ("typescript/javascript", {".js", ".jsx", ".ts", ".tsx"}),
            ("rust", {".rs"}),
            ("go", {".go"}),
            ("java/kotlin", {".java", ".kt", ".kts"}),
            ("swift", {".swift"}),
            ("php", {".php"}),
            ("ruby", {".rb"}),
        ):
            if suffixes & extensions:
                languages.append(name)
        managers = [
            name for name, marker in (
                ("uv", "uv.lock"), ("npm", "package-lock.json"),
                ("pnpm", "pnpm-lock.yaml"), ("yarn", "yarn.lock"),
                ("cargo", "Cargo.lock"), ("go", "go.mod"),
            )
            if (resolved / marker).exists()
        ]
        important_names = {
            "README.md", "AGENTS.md", "DECISION.md", "DECISIONS.md",
            "MEMORY.md", "pyproject.toml", "package.json", "Cargo.toml", "go.mod",
        }
        entrypoint_names = {
            "main.py", "app.py", "__main__.py", "index.js", "index.ts",
            "app.tsx", "main.tsx", "main.rs", "main.go",
        }
        branch, dirty = _git_status(resolved)
        result = WorkspaceMap(
            root=resolved,
            file_count=len(files),
            truncated=truncated,
            languages=tuple(languages),
            package_managers=tuple(managers),
            important_paths=tuple(p for p in relative_files if Path(p).name in important_names),
            entrypoints=tuple(p for p in relative_files if Path(p).name in entrypoint_names),
            docs=tuple(p for p in relative_files if Path(p).suffix.lower() == ".md"),
            tests=tuple(
                p for p in relative_files
                if "test" in Path(p).name.lower() or "tests" in Path(p).parts
            ),
            commands=tuple(_commands(resolved)),
            git_branch=branch,
            git_dirty=dirty,
        )
        self._cache[resolved] = (time.monotonic(), result)
        return result


def _commands(root: Path) -> list[str]:
    commands: list[str] = []
    package = root / "package.json"
    if package.is_file():
        try:
            scripts = json.loads(package.read_text(encoding="utf-8")).get("scripts", {})
            if isinstance(scripts, dict):
                commands.extend(f"npm run {name}" for name in sorted(scripts))
        except (OSError, json.JSONDecodeError):
            pass
    if (root / "pyproject.toml").is_file():
        commands.append("uv run pytest")
    if (root / "Cargo.toml").is_file():
        commands.append("cargo test")
    if (root / "go.mod").is_file():
        commands.append("go test ./...")
    return commands


def _git_status(root: Path) -> tuple[str | None, bool | None]:
    try:
        branch = subprocess.run(
            ["git", "branch", "--show-current"], cwd=root, capture_output=True,
            text=True, timeout=2, check=False,
        )
        status = subprocess.run(
            ["git", "status", "--porcelain"], cwd=root, capture_output=True,
            text=True, timeout=2, check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None, None
    if branch.returncode != 0 or status.returncode != 0:
        return None, None
    return branch.stdout.strip() or "detached", bool(status.stdout.strip())
